services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
networks:
  postgres:
volumes:
  postgres: